/* Generated by bin2c, do not edit manually */
#ifndef shaggy_h_included
#define shaggy_h_included

/* Contents of file .\shaggy.rgba */
extern const long int shaggy_rgba_size;
extern const unsigned char shaggy_rgba[1048576];

#endif    /* __shaggy_h_included */
